//! Cloud-init #cloud-config snippet generation.
//!
//! Snippets are written as plain YAML (no library — keeps the dep tree small
//! and the output diff-readable). Strings are sanitized with quoted YAML
//! literals to avoid escape footguns.

use anyhow::{Context, Result};
use inquire::{Confirm, MultiSelect, Select, Text};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug)]
pub struct Profile {
    /// Username of the primary account that gets passwordless sudo.
    pub username: String,
    /// Optional `ssh_import_id` value (e.g. "gh:octocat" or "lp:octocat").
    /// Empty string means none.
    pub ssh_import_id: String,
    /// Inline `ssh_authorized_keys` entries.
    pub ssh_keys: Vec<String>,
    /// apt packages to install.
    pub packages: Vec<String>,
    /// Optional shell commands to run on first boot.
    pub runcmd: Vec<String>,
    /// Reboot after first-boot config (useful when packages pull a new kernel).
    pub reboot_after: bool,
}

impl Profile {
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("#cloud-config\n");
        out.push_str("# Generated by proxmox-imgctl\n\n");

        out.push_str("users:\n");
        out.push_str("  - default\n");
        out.push_str(&format!("  - name: {}\n", yaml_str(&self.username)));
        out.push_str("    sudo: ALL=(ALL) NOPASSWD:ALL\n");
        out.push_str("    shell: /bin/bash\n");
        out.push_str("    lock_passwd: true\n");
        if !self.ssh_import_id.is_empty() {
            out.push_str("    ssh_import_id:\n");
            out.push_str(&format!("      - {}\n", yaml_str(&self.ssh_import_id)));
        }
        if !self.ssh_keys.is_empty() {
            out.push_str("    ssh_authorized_keys:\n");
            for k in &self.ssh_keys {
                out.push_str(&format!("      - {}\n", yaml_str(k)));
            }
        }

        if !self.packages.is_empty() {
            out.push_str("\npackage_update: true\n");
            out.push_str("package_upgrade: true\n");
            out.push_str("packages:\n");
            for p in &self.packages {
                out.push_str(&format!("  - {}\n", yaml_str(p)));
            }
        }

        if !self.runcmd.is_empty() {
            out.push_str("\nruncmd:\n");
            for c in &self.runcmd {
                out.push_str(&format!("  - {}\n", yaml_str(c)));
            }
        }

        if self.reboot_after {
            out.push_str("\npower_state:\n  mode: reboot\n  delay: 1\n  condition: true\n");
        }
        out
    }
}

fn yaml_str(s: &str) -> String {
    // Always double-quote so colons/hashes/etc are safe.
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

const BUILTINS: &[(&str, &str)] = &[
    ("minimal", "single user, no extra packages"),
    (
        "dev",
        "user + git, build-essential, curl, vim, htop, tmux, jq",
    ),
    (
        "docker",
        "user + Docker engine via apt repo (runs convenience installer)",
    ),
];

pub fn pick_or_generate(snippet_dir: &Path, dry_run: bool) -> Result<PathBuf> {
    if !dry_run {
        fs::create_dir_all(snippet_dir)
            .with_context(|| format!("creating snippet dir {}", snippet_dir.display()))?;
    }

    let mut options: Vec<String> = BUILTINS
        .iter()
        .map(|(n, d)| format!("[builtin] {n} — {d}"))
        .collect();

    // Existing snippets in the dir.
    let mut existing: Vec<PathBuf> = Vec::new();
    if let Ok(read) = fs::read_dir(snippet_dir) {
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "yaml" || e == "yml") {
                existing.push(path);
            }
        }
    }
    existing.sort();
    for p in &existing {
        options.push(format!(
            "[existing] {}",
            p.file_name().unwrap().to_string_lossy()
        ));
    }
    options.push("[generate interactively]".into());

    let pick = Select::new("Cloud-init profile:", options.clone()).prompt()?;

    if let Some(idx) = options.iter().position(|x| x == &pick) {
        if idx < BUILTINS.len() {
            let name = BUILTINS[idx].0;
            return materialize_builtin(name, snippet_dir, dry_run);
        }
        if idx < BUILTINS.len() + existing.len() {
            return Ok(existing[idx - BUILTINS.len()].clone());
        }
    }
    // Generate interactively.
    let p = generate_interactive()?;
    let filename = Text::new("Snippet filename:")
        .with_default("custom.yaml")
        .prompt()?;
    let path = snippet_dir.join(filename);
    write_snippet(&path, &p.render(), dry_run)?;
    Ok(path)
}

fn write_snippet(path: &Path, content: &str, dry_run: bool) -> Result<()> {
    if dry_run {
        println!(
            "[dry-run] would write {} ({} bytes):",
            path.display(),
            content.len()
        );
        for line in content.lines() {
            println!("  | {line}");
        }
        return Ok(());
    }
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("Wrote {}", path.display());
    Ok(())
}

fn materialize_builtin(name: &str, snippet_dir: &Path, dry_run: bool) -> Result<PathBuf> {
    let username = Text::new("Primary username:")
        .with_default("admin")
        .prompt()?;
    let ssh_import_id = Text::new("ssh_import_id (e.g. gh:octocat, blank to skip):")
        .with_default("")
        .prompt()?;

    let mut p = Profile {
        username,
        ssh_import_id,
        ssh_keys: Vec::new(),
        packages: Vec::new(),
        runcmd: Vec::new(),
        reboot_after: false,
    };

    match name {
        "minimal" => {}
        "dev" => {
            p.packages = vec![
                "git",
                "build-essential",
                "curl",
                "vim",
                "htop",
                "tmux",
                "jq",
                "ca-certificates",
            ]
            .into_iter()
            .map(String::from)
            .collect();
        }
        "docker" => {
            p.packages = vec!["ca-certificates", "curl", "gnupg"]
                .into_iter()
                .map(String::from)
                .collect();
            p.runcmd = vec![
                "curl -fsSL https://get.docker.com | sh".to_string(),
                format!("usermod -aG docker {}", p.username),
            ];
        }
        _ => unreachable!(),
    }

    p.reboot_after = Confirm::new("Reboot after first-boot config?")
        .with_default(false)
        .prompt()?;

    let filename = Text::new("Snippet filename:")
        .with_default(&format!("{name}.yaml"))
        .prompt()?;
    let path = snippet_dir.join(filename);
    write_snippet(&path, &p.render(), dry_run)?;
    Ok(path)
}

fn generate_interactive() -> Result<Profile> {
    let username = Text::new("Primary username:")
        .with_default("admin")
        .prompt()?;
    let ssh_import_id = Text::new("ssh_import_id (e.g. gh:octocat, blank to skip):")
        .with_default("")
        .prompt()?;

    let presets = vec![
        "git",
        "build-essential",
        "curl",
        "vim",
        "htop",
        "tmux",
        "jq",
        "ca-certificates",
        "wget",
        "rsync",
        "unzip",
    ];
    let chosen =
        MultiSelect::new("Pick packages (space toggles, enter confirms):", presets).prompt()?;
    let extra = Text::new("Extra packages (space-separated, blank for none):")
        .with_default("")
        .prompt()?;

    let mut packages: Vec<String> = chosen.into_iter().map(String::from).collect();
    for tok in extra.split_whitespace() {
        packages.push(tok.to_string());
    }

    let runcmd_raw = Text::new("First-boot commands (semicolon-separated, blank for none):")
        .with_default("")
        .prompt()?;
    let runcmd = runcmd_raw
        .split(';')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(String::from)
        .collect();

    let reboot_after = Confirm::new("Reboot after first-boot config?")
        .with_default(false)
        .prompt()?;

    Ok(Profile {
        username,
        ssh_import_id,
        ssh_keys: Vec::new(),
        packages,
        runcmd,
        reboot_after,
    })
}
